server:
http_listen_port: ${PORT}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: $LOKI_URL
    basic_auth:
      username: $LOKI_USERNAME
      password: $LOKI_PASSWORD

scrape_configs:
  - job_name: heroku
    heroku_drain:
      labels:
        job: heroku
        app: tmi-server
    relabel_configs:
      - source_labels: [app]
        target_label: heroku_app
