server:
  http_listen_port: ${PORT}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
    basic_auth:
      username: ${LOKI_USERNAME}
      password: ${LOKI_PASSWORD}

scrape_configs:
  - job_name: heroku
    heroku_drain:
      labels:
        job: heroku
        app: tmi-server
        environment: heroku
        source: heroku-dyno
    relabel_configs:
      - source_labels: [__heroku_drain_dyno]
        target_label: dyno
      - source_labels: [__heroku_drain_app]
        target_label: heroku_app
